name: Run TypeScript and Parallel Tasks

on: [push, pull_request, workflow_dispatch]

jobs:
  generate_number:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.github/workflows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: npm install
        run: npm i

      - name: Run TypeScript file
        id: number
        run: echo "::set-output name=times::$(npx ts-node get_tests.ts)"

      - name: Generate matrix
        id: matrix
        run: echo "::set-output name=matrix::[$(seq 1 ${{ steps.number.outputs.times }} | sed 's/.*/"&"/' | paste -sd ',' -)]"

      - name: Print Matrix
        run: echo "${{ steps.matrix.outputs.matrix }}"

  print_hello_world:
    needs: generate_number
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run: ${{fromJson(needs.generate_number.outputs.matrix)}}
    steps:
      - name: Print Hello World
        run: npx ts-node output.ts ${{ matrix.run }}
