name: Run TypeScript and Parallel Tasks

on: [push, pull_request, workflow_dispatch]

jobs:
  generate_number:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    outputs:
      shards: ${{ steps.number.outputs.shards }}
      matrix: ${{ steps.matrix.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: npm install
        run: npm i

      - name: Run TypeScript file
        id: number
        run: |
          result=$(npx ts-node get_tests.ts)
          count=$(echo $result | jq length)
          echo "shards=$count" >> "$GITHUB_OUTPUT"

      - name: Upload tests distribution JSON artifact
        uses: actions/upload-artifact@v2
        with:
          name: tests-distribution-artifact
          path: ./scripts/tests_distribution.json

      - name: Generate matrix
        id: matrix
        run: echo "matrix=[$(seq 1 ${{ steps.number.outputs.shards }} | sed 's/.*/"&"/' | paste -sd ',' -)]" >> "$GITHUB_OUTPUT"

      # - name: Print Matrix
      #   run: echo "${{ steps.matrix.outputs.matrix }}"

  print_hello_world:
    needs: generate_number
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    strategy:
      matrix:
        run: ${{fromJson(needs.generate_number.outputs.matrix)}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: npm install
        run: npm i

      - name: Print Hello World
        run: |
          npx ts-node output.ts ${{ matrix.run }}

      - name: Download JSON artifact
        uses: actions/download-artifact@v2
        with:
          name: tests-distribution-artifact

      - name: Print tests
        run: |
          cat ./tests_distribution.json
